// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGaAGBjRXxAK58GUCeScPW65hpBl7KRnE',
    appId: '1:151876687104:web:d4eafc919df39756994fe5',
    messagingSenderId: '151876687104',
    projectId: 'chatapp-5d0a9',
    authDomain: 'chatapp-5d0a9.firebaseapp.com',
    storageBucket: 'chatapp-5d0a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEbqRPGYRS0bhjtFRUQzAj_msEPW1ZKA',
    appId: '1:151876687104:android:567d8bf46b6e4920994fe5',
    messagingSenderId: '151876687104',
    projectId: 'chatapp-5d0a9',
    storageBucket: 'chatapp-5d0a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeKhlY2btSmoqorM2F5vUyw9RgTjbY82c',
    appId: '1:151876687104:ios:5a8d0e1056265254994fe5',
    messagingSenderId: '151876687104',
    projectId: 'chatapp-5d0a9',
    storageBucket: 'chatapp-5d0a9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeKhlY2btSmoqorM2F5vUyw9RgTjbY82c',
    appId: '1:151876687104:ios:ebbc1ed436feaad2994fe5',
    messagingSenderId: '151876687104',
    projectId: 'chatapp-5d0a9',
    storageBucket: 'chatapp-5d0a9.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
